### ISSUE TITLE
model weight for CHUS split gives result different from paper

### ISSUE THREAD

**Issue by vokcow** [iantsen/hecktor#5]
Hi Andrei,

The weight `s1_best_model_weights.pt` for the `train_val_split_1.pkl` split (CHUS center) produces an average Dice score of `0.751`, different from the value `0.744` reported in the paper. 

All other weights, when evaluated in their respective splits, match the paper results. Could the weight `s1_best_model_weights.pt` correspond to a model trained on a split different than `train_val_split_1.pkl` ?

Thanks in advance,

Victor

**Comment by iantsen** [comment]
Hi Victor,

> All other weights, when evaluated in their respective splits, match the paper results. Could the weight `s1_best_model_weights.pt` correspond to a model trained on a split different than `train_val_split_1.pkl` ?

No, the weights correspond to the split 1 (CHUS center) for sure. I checked that today.
I think, I know the reason for different scores. I ran many different experiments in parallel on a GPU cluster. There was a time limit for some GPUs, so sometimes I had to resume training some models from intermediate results (e.g. after 100 epoch) to reach the total number of training epochs. In case of the s1 model, I might just mixed up the intermidiate weights and the final weights. That's why there is this small discrepancy. However, it is still a bit strange, since the ensemble produced the same results.  

Here is the performance on the split 1 (s1), that I had during the competition:
[expected_results_s1.zip](https://github.com/iantsen/hecktor/files/6811761/expected_results_s1.zip)
